extends TabContainer
class_name ColorsGenerators_Container
## A container for different color theme generators, organized as tabs.
## It allows switching between various color generation methods (e.g., random, gradient)
## and delegates the color generation task to the currently active generator.
##
## This class extends TabContainer, where each tab is expected to be an instance
## of a class that implements the `generate_colors_theme()` method,
## ideally extending `ColorsGenerator`.

## Calls the `generate_colors_theme()` method on the currently selected tab's control.
## It assumes that the current tab's control is a `ColorsGenerator` type or a class
## that implements the `generate_colors_theme()` method.
## @return An Array of Color objects generated by the current generator, or an empty array if
##         the current tab's control is not a `ColorsGenerator`.

func generate_colors() -> Array[Color]:
	var current = get_current_tab_control()
	if current is ColorsGenerator:
		return current.generate_colors_theme()
	return []


## Returns the control of the currently active tab.
## This can be used to access the currently selected color generator instance.
## @return The currently active Object (Node) in the TabContainer.

func get_current_generator() -> Object:
	return get_current_tab_control()
