extends TabContainer
class_name GradientsGenerators_Container
## A container for different gradient generators, organized as tabs.
## This class extends `TabContainer`, where each tab is expected to be an instance
## of a class that implements the `generate_gradients()` method,
## ideally extending an abstract `AGradientsGenerator` .
## It delegates the gradient generation task to the currently active generator.

## Calls the `generate_gradients()` method on the currently selected tab's control.
## It assumes that the current tab's control is a `AGradientsGenerator` type or a class
## that implements the `generate_gradients()` method.
## @param colors An Array of Color objects to be used as input for gradient generation.
## @return An Array of Color objects (or other gradient representation) generated by the current generator.

func generate_gradients(colors:Array[Color]) -> Array[Gradient]:
	var current = get_current_tab_control()
	if current is AGradientsGenerator:
		# It is expected that the current generator will handle the colors array.
		return current.generate_gradients(colors)

	printerr("Error: 'generate_gradients()' called on a non-GradientsGenerator control.")
	return []

## Returns the control of the currently active tab.
## This can be used to access the currently selected gradient generator instance.
## @return The currently active Object (Node) in the TabContainer.

func get_current_generator() -> Object:	return get_current_tab_control()
